name: myportfolio
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.0
  font_awesome_flutter: ^10.6.0
  simple_animations: ^5.0.2
  responsive_framework: ^1.1.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/tetbee/

  fonts:
    - family: lb
      fonts:
        - asset: assets/fonts/league-b.ttf
    - family: ll
      fonts:
        - asset: assets/fonts/league-l.ttf
    - family: lm
      fonts:
        - asset: assets/fonts/league-m.ttf
    - family: lr
      fonts:
        - asset: assets/fonts/league-r.ttf
